<a href="https://colab.research.google.com/github/Ajitgupta31/PYTHON-Programming/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## DataType in Python

String
Integer
float
bool
complex

**DataTypes in numpy**

# i - integer
# c - complex
# n - timedelta (t-t') small change in time
# M - datatime
# o - Object
# S - String
# U - unicode string
# V - fixed chunk memory for other

In [ ]:
import numpy as np
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.__version__

'2.0.2'

In [ ]:
import sys
sys.version

'3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]'

**Creating Arrays**

In [ ]:
my_list =[0,1,2,3,5,6,4]
my_list

[0, 1, 2, 3, 5, 6, 4]

In [ ]:
type(my_list)

list

**Below code we are converting list to array**

In [ ]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 5, 6, 4])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.arange(3.0)

array([0., 1., 2.])

In [ ]:
np.arange(3.5)

array([0., 1., 2., 3.])

***Array creation :coversion from other Python structure***

In [ ]:
import numpy as np

In [ ]:
listarray = np.array([[1,2,3],[5,8,5],[7,4,8]])
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [7, 4, 8]])

In [ ]:
listarray.dtype

dtype('int64')

In [ ]:
listarray.shape

(3, 3)

In [ ]:
listarray.size

9

In [ ]:
np.array({33,45,32})


array({32, 33, 45}, dtype=object)

In [ ]:
zeroes= np.zeros((2,5))
zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
rng =np.arange(17)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
lspace = np.linspace(1,50,10)
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [ ]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [ ]:
np.linspace(1,5,6)

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [ ]:
emp = np.empty((4,6))
emp

array([[-0.25, -0.5 ,  0.  , -0.25,  0.25, -0.5 ],
       [ 0.5 , -0.25,  0.25,  0.  ,  0.5 ,  0.25],
       [ 0.25,  0.5 ,  0.  ,  0.25, -0.25,  0.5 ],
       [-0.5 ,  0.25, -0.25,  0.  , -0.5 , -0.25]])

In [ ]:
emp_like = np.empty_like(lspace)
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [ ]:
ide = np.identity(30)
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0

In [ ]:
ide.shape

(30, 30)

In [ ]:
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr.shape

(99,)

In [ ]:
x=[[1,2,3],[4,5,6],[3,5,9]]

In [ ]:
ar=np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [3, 5, 9]])

In [ ]:
ar.sum(axis=0)


array([ 8, 12, 18])

In [ ]:
ar.sum(axis=1)

array([ 6, 15, 17])

In [ ]:
ar.T

array([[1, 4, 3],
       [2, 5, 5],
       [3, 6, 9]])

In [ ]:
ar.flat

In [ ]:
for i in ar.flat:
  print(i)

1
2
3
4
5
6
3
5
9


In [ ]:
ar.ndim

2

In [ ]:
arr.ndim

1

In [ ]:
ar.size

9

In [ ]:
ar.nbytes

72

In [ ]:
arr.nbytes

792

In [ ]:
a =np.array([1,3,7,8])
a

array([1, 3, 7, 8])

In [ ]:
a.argmax()

np.int64(3)

In [ ]:
a.argmin()

np.int64(0)

In [ ]:
a.argsort()

array([0, 1, 2, 3])

In [ ]:
ar.argmin()

np.int64(0)

In [ ]:
ar.argmax()

np.int64(8)

In [ ]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [3, 5, 9]])

In [ ]:
ar.argmax(axis=0)

array([1, 1, 2])

In [ ]:
ar.argmax(axis=1)

array([2, 2, 2])

In [ ]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [2, 1, 1],
       [1, 2, 2]])

In [ ]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 3, 5, 9])

In [ ]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [3],
       [5],
       [9]])

In [ ]:
ar2 = np.array([[1, 2, 1],  [3,2,4],[3,5,1]])
ar2

array([[1, 2, 1],
       [3, 2, 4],
       [3, 5, 1]])

In [ ]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [3, 5, 9]])

In [ ]:
ar+ar2

array([[ 2,  4,  4],
       [ 7,  7, 10],
       [ 6, 10, 10]])

In [ ]:
ar*ar2

array([[ 1,  4,  3],
       [12, 10, 24],
       [ 9, 25,  9]])

In [ ]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [1.73205081, 2.23606798, 3.        ]])

In [ ]:
np.sqrt(ar2)

array([[1.        , 1.41421356, 1.        ],
       [1.73205081, 1.41421356, 2.        ],
       [1.73205081, 2.23606798, 1.        ]])

In [ ]:
ar.sum()

np.int64(38)

In [ ]:
np.where(ar>5)

(array([1, 2]), array([2, 2]))

In [ ]:
type(np.where(ar>5))

tuple

In [ ]:
np.count_nonzero(ar)

9

In [ ]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [ ]:
ar[1,2]=0

In [ ]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 0, 1, 2]))

In [ ]:
import sys

In [ ]:
cha_r =[0,5,44,5]

In [ ]:
np_ar =np.array(cha_r)
sys.getsizeof(1)*len(cha_r)

112

In [ ]:
np_ar.itemsize*np_ar.size

32

In [1]:
import numpy as np

In [2]:
ar =np.array([1,3,5,6])
print(ar.dtype)

int64


In [3]:
ar =np.array(["ajit",1,3,5,6])
print(ar.dtype)

<U21


In [ ]:
#what if a value can not be converted
#Valuerror through  : if valueerror raised when the types of passed argument  to a function is unexpected/incorrect

In [5]:
a = np.array(['a',1,4,6], dtype ='i')
print(a)

ValueError: invalid literal for int() with base 10: 'a'

In [6]:
# Change the data type from integer to boolean

a1 = np.array([1,0,4])
a2 = a1.astype(bool)
print(a1)
print(a2.dtype)

[1 0 4]
bool


In [8]:
#Correct syntax

#np.createArray([1,2,3,4])
#np.array[1,2,3,4,5]
np.object([1,2,3,4,45])
#none

/tmp/ipykernel_6531/1128165274.py:5: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  np.object([1,2,3,4,45])


AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations