## DataType in Python

String
Integer
float
bool
complex

**DataTypes in numpy**

# i - integer
# c - complex
# n - timedelta (t-t') small change in time
# M - datatime
# o - Object
# S - String
# U - unicode string
# V - fixed chunk memory for other

**NUMPY**

NumPy (Numerical Python) is a foundational open-source library for scientific computing in Python, providing support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on them.

In [ ]:
import numpy as np
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.__version__

'2.0.2'

In [ ]:
import sys
sys.version

'3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]'

**Creating Arrays**

In [ ]:
my_list =[0,1,2,3,5,6,4]
my_list

[0, 1, 2, 3, 5, 6, 4]

In [ ]:
type(my_list)

list

**Below code we are converting list to array**

In [ ]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 5, 6, 4])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.arange(3.0)

array([0., 1., 2.])

In [ ]:
np.arange(3.5)

array([0., 1., 2., 3.])

***Array creation :coversion from other Python structure***

In [ ]:
import numpy as np

In [ ]:
listarray = np.array([[1,2,3],[5,8,5],[7,4,8]])
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [7, 4, 8]])

In [ ]:
listarray.dtype

dtype('int64')

In [ ]:
listarray.shape

(3, 3)

In [ ]:
listarray.size

9

In [ ]:
np.array({33,45,32})


array({32, 33, 45}, dtype=object)

In [ ]:
zeroes= np.zeros((2,5))
zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
rng =np.arange(17)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
lspace = np.linspace(1,50,10)
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [ ]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [ ]:
np.linspace(1,5,6)

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [ ]:
emp = np.empty((4,6))
emp

array([[-0.25, -0.5 ,  0.  , -0.25,  0.25, -0.5 ],
       [ 0.5 , -0.25,  0.25,  0.  ,  0.5 ,  0.25],
       [ 0.25,  0.5 ,  0.  ,  0.25, -0.25,  0.5 ],
       [-0.5 ,  0.25, -0.25,  0.  , -0.5 , -0.25]])

In [ ]:
emp_like = np.empty_like(lspace)
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [ ]:
ide = np.identity(30)
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0

In [ ]:
ide.shape

(30, 30)

In [ ]:
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr.shape

(99,)

In [ ]:
x=[[1,2,3],[4,5,6],[3,5,9]]

In [ ]:
ar=np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [3, 5, 9]])

In [ ]:
ar.sum(axis=0)


array([ 8, 12, 18])

In [ ]:
ar.sum(axis=1)

array([ 6, 15, 17])

In [ ]:
ar.T

array([[1, 4, 3],
       [2, 5, 5],
       [3, 6, 9]])

In [ ]:
ar.flat

In [ ]:
for i in ar.flat:
  print(i)

1
2
3
4
5
6
3
5
9


In [ ]:
ar.ndim

2

In [ ]:
arr.ndim

1

In [ ]:
ar.size

9

In [ ]:
ar.nbytes

72

In [ ]:
arr.nbytes

792

In [ ]:
a =np.array([1,3,7,8])
a

array([1, 3, 7, 8])

In [ ]:
a.argmax()

np.int64(3)

In [ ]:
a.argmin()

np.int64(0)

In [ ]:
a.argsort()

array([0, 1, 2, 3])

In [ ]:
ar.argmin()

np.int64(0)

In [ ]:
ar.argmax()

np.int64(8)

In [ ]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [3, 5, 9]])

In [ ]:
ar.argmax(axis=0)

array([1, 1, 2])

In [ ]:
ar.argmax(axis=1)

array([2, 2, 2])

In [ ]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [2, 1, 1],
       [1, 2, 2]])

In [ ]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 3, 5, 9])

In [ ]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [3],
       [5],
       [9]])

In [ ]:
ar2 = np.array([[1, 2, 1],  [3,2,4],[3,5,1]])
ar2

array([[1, 2, 1],
       [3, 2, 4],
       [3, 5, 1]])

In [ ]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [3, 5, 9]])

In [ ]:
ar+ar2

array([[ 2,  4,  4],
       [ 7,  7, 10],
       [ 6, 10, 10]])

In [ ]:
ar*ar2

array([[ 1,  4,  3],
       [12, 10, 24],
       [ 9, 25,  9]])

In [ ]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [1.73205081, 2.23606798, 3.        ]])

In [ ]:
np.sqrt(ar2)

array([[1.        , 1.41421356, 1.        ],
       [1.73205081, 1.41421356, 2.        ],
       [1.73205081, 2.23606798, 1.        ]])

In [ ]:
ar.sum()

np.int64(38)

In [ ]:
np.where(ar>5)

(array([1, 2]), array([2, 2]))

In [ ]:
type(np.where(ar>5))

tuple

In [ ]:
np.count_nonzero(ar)

9

In [ ]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [ ]:
ar[1,2]=0

In [ ]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 0, 1, 2]))

In [ ]:
import sys

In [ ]:
cha_r =[0,5,44,5]

In [ ]:
np_ar =np.array(cha_r)
sys.getsizeof(1)*len(cha_r)

112

In [ ]:
np_ar.itemsize*np_ar.size

32

In [ ]:
import numpy as np

In [ ]:
ar =np.array([1,3,5,6])
print(ar.dtype)

int64


In [ ]:
ar =np.array(["ajit",1,3,5,6])
print(ar.dtype)

<U21


In [ ]:
#what if a value can not be converted
#Valuerror through  : if valueerror raised when the types of passed argument  to a function is unexpected/incorrect

In [ ]:
a = np.array(['a',1,4,6], dtype ='i')
print(a)

ValueError: invalid literal for int() with base 10: 'a'

In [ ]:
# Change the data type from integer to boolean

a1 = np.array([1,0,4])
a2 = a1.astype(bool)
print(a1)
print(a2.dtype)

[1 0 4]
bool


In [ ]:
#Correct syntax

#np.createArray([1,2,3,4])
#np.array[1,2,3,4,5]
np.object([1,2,3,4,45])
#none

/tmp/ipykernel_6531/1128165274.py:5: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  np.object([1,2,3,4,45])


AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

# We Learn important function

In [ ]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(3.0)

array([0., 1., 2.])

In [ ]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(20,10)

array([], dtype=int64)

In [ ]:
np.arange(10,20,2)


array([10, 12, 14, 16, 18])

In [ ]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [ ]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [ ]:
np.arange()

TypeError: arange() requires stop to be specified.

In [ ]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [ ]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.zeros((2,2),dtype =int)

array([[0, 0],
       [0, 0]])

In [ ]:
zero = np.zeros([2,2])
print (zero)

print('######')

print(type(zero))

[[0. 0.]
 [0. 0.]]
######
<class 'numpy.ndarray'>


In [ ]:
np.zeros(2,10)

TypeError: Cannot interpret '10' as a data type

In [ ]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [ ]:
np.zeros((5,10),dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
n =(6,7)
n1 =(6,8)
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
print(np.zeros(n,dtype =int))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones(4,dtype = int)

array([1, 1, 1, 1])

In [ ]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones((4,6), dtype=int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [ ]:
np.twos(3)
# module 'numpy' has no attribute 'twos'

AttributeError: module 'numpy' has no attribute 'twos'

In [ ]:
np.three((3,4))

AttributeError: module 'numpy' has no attribute 'three'

In [ ]:
rand(3,2)


NameError: name 'rand' is not defined

In [ ]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [ ]:

np.random.rand(3,2)

array([[0.88533892, 0.29265021],
       [0.39218491, 0.08731779],
       [0.35016219, 0.93281403]])

In [ ]:
np.random.rand(6)

array([0.1174123 , 0.16729996, 0.97379215, 0.14037967, 0.63730905,
       0.00109668])

In [ ]:
np.randam.randint(6)

AttributeError: module 'numpy' has no attribute 'randam'

In [ ]:
np.random.randint(3,5)

4

In [ ]:
np.random.randint(3,50)

18

In [ ]:
np.random.randint(2,4)

2

In [ ]:
np.random.randint(2,6)


2

In [ ]:
np.random.randint(2,20)

7

In [ ]:
np.random.randint(10,20,5)

array([14, 15, 14, 14, 18])

In [ ]:
np.random.randint(1,6,4)

array([5, 3, 2, 5])

In [ ]:
np.random.randint(1,100,(2,12))

array([[73, 26, 31, 67, 11, 25, 10, 44,  3, 60, 92, 56],
       [49, 32, 48, 49, 63, 17, 13, 46, 91, 68, 81, 59]])

In [ ]:
np.random.randint(10,40,(10,10))

array([[12, 38, 33, 32, 32, 25, 22, 27, 33, 22],
       [37, 37, 16, 34, 12, 33, 22, 19, 10, 31],
       [29, 26, 34, 20, 16, 10, 22, 21, 23, 30],
       [31, 26, 31, 21, 26, 37, 31, 15, 12, 30],
       [21, 17, 27, 35, 22, 21, 39, 25, 14, 30],
       [13, 26, 29, 15, 37, 37, 26, 36, 25, 23],
       [23, 23, 34, 37, 14, 14, 10, 32, 31, 35],
       [28, 26, 19, 24, 11, 33, 24, 39, 21, 11],
       [23, 23, 37, 21, 18, 18, 22, 18, 18, 13],
       [18, 12, 18, 24, 16, 25, 11, 32, 22, 14]])

In [ ]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [ ]:
np.arange(1,13).reshape(6,3)

ValueError: cannot reshape array of size 12 into shape (6,3)

# String Slicing

In [ ]:
np.random.randint(1,100,(2,12))

array([[48, 58, 36, 11, 42,  8, 89, 96, 91,  5, 29, 95],
       [92, 12,  2, 36, 95, 38, 94, 60, 70, 58, 30, 59]])

In [ ]:
a = np.random.randint(10,20,(5,4))
a

array([[19, 12, 14, 16],
       [17, 10, 13, 11],
       [14, 10, 16, 11],
       [11, 14, 12, 18],
       [19, 13, 18, 17]])

In [ ]:
a[:]

array([[16, 10, 18, 14],
       [13, 11, 15, 10],
       [16, 18, 13, 10],
       [17, 18, 14, 15],
       [19, 15, 15, 14]])

In [ ]:
a[1:3]

array([[17, 10, 13, 11],
       [14, 10, 16, 11]])

In [ ]:
a[1,2]

np.int64(15)

In [ ]:
a[1,-1]

np.int64(11)

In [ ]:
a[-4:2]

array([[17, 10, 13, 11]])

# Operation

In [ ]:
b =np.random.randint(10,20,10)
b

array([17, 13, 10, 11, 14, 13, 16, 16, 14, 13])

In [ ]:
id(b)

133299707806800

In [ ]:
arr =np.random.randint(10,100,(10,10))
arr

array([[77, 58, 64, 22, 66, 14, 95, 41, 49, 71],
       [84, 46, 24, 69, 25, 11, 77, 38, 29, 97],
       [33, 14, 54, 85, 23, 53, 52, 65, 93, 57],
       [66, 59, 94, 85, 36, 82, 65, 96, 92, 51],
       [12, 49, 81, 12, 41, 75, 31, 64, 49, 58],
       [74, 34, 69, 45, 21, 26, 70, 34, 78, 18],
       [38, 56, 37, 59, 52, 16, 69, 87, 72, 92],
       [61, 36, 73, 85, 41, 56, 26, 98, 44, 56],
       [74, 74, 79, 34, 76, 45, 48, 85, 49, 17],
       [83, 35, 42, 27, 36, 78, 24, 79, 60, 74]])

In [ ]:
arr[::-1]

array([[83, 35, 42, 27, 36, 78, 24, 79, 60, 74],
       [74, 74, 79, 34, 76, 45, 48, 85, 49, 17],
       [61, 36, 73, 85, 41, 56, 26, 98, 44, 56],
       [38, 56, 37, 59, 52, 16, 69, 87, 72, 92],
       [74, 34, 69, 45, 21, 26, 70, 34, 78, 18],
       [12, 49, 81, 12, 41, 75, 31, 64, 49, 58],
       [66, 59, 94, 85, 36, 82, 65, 96, 92, 51],
       [33, 14, 54, 85, 23, 53, 52, 65, 93, 57],
       [84, 46, 24, 69, 25, 11, 77, 38, 29, 97],
       [77, 58, 64, 22, 66, 14, 95, 41, 49, 71]])

In [ ]:
arr[::-2]

array([[83, 35, 42, 27, 36, 78, 24, 79, 60, 74],
       [61, 36, 73, 85, 41, 56, 26, 98, 44, 56],
       [74, 34, 69, 45, 21, 26, 70, 34, 78, 18],
       [66, 59, 94, 85, 36, 82, 65, 96, 92, 51],
       [84, 46, 24, 69, 25, 11, 77, 38, 29, 97]])

In [ ]:
arr[::-3]

array([[83, 35, 42, 27, 36, 78, 24, 79, 60, 74],
       [38, 56, 37, 59, 52, 16, 69, 87, 72, 92],
       [66, 59, 94, 85, 36, 82, 65, 96, 92, 51],
       [77, 58, 64, 22, 66, 14, 95, 41, 49, 71]])

In [ ]:
arr[:-3]

array([[77, 58, 64, 22, 66, 14, 95, 41, 49, 71],
       [84, 46, 24, 69, 25, 11, 77, 38, 29, 97],
       [33, 14, 54, 85, 23, 53, 52, 65, 93, 57],
       [66, 59, 94, 85, 36, 82, 65, 96, 92, 51],
       [12, 49, 81, 12, 41, 75, 31, 64, 49, 58],
       [74, 34, 69, 45, 21, 26, 70, 34, 78, 18],
       [38, 56, 37, 59, 52, 16, 69, 87, 72, 92]])

In [ ]:
arr[3:]

array([[66, 59, 94, 85, 36, 82, 65, 96, 92, 51],
       [12, 49, 81, 12, 41, 75, 31, 64, 49, 58],
       [74, 34, 69, 45, 21, 26, 70, 34, 78, 18],
       [38, 56, 37, 59, 52, 16, 69, 87, 72, 92],
       [61, 36, 73, 85, 41, 56, 26, 98, 44, 56],
       [74, 74, 79, 34, 76, 45, 48, 85, 49, 17],
       [83, 35, 42, 27, 36, 78, 24, 79, 60, 74]])

In [ ]:
arr.max()

np.int64(98)

In [ ]:
arr.min()

np.int64(11)

In [ ]:
arr.mean()

np.float64(55.26)

In [ ]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [ ]:
from numpy import *
c = array([1,2,3,4])
median(c)



np.float64(2.5)

# Indexing

In [ ]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
row =4
col =5

In [ ]:
row

4

In [ ]:
col

5

In [ ]:
mat[row, col]

np.int64(45)

In [ ]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [ ]:
mat[:,col]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [ ]:
mat[:,4]

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [ ]:
mat[0:10:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [ ]:
mat[:-1]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [ ]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [ ]:
mat[1:2,2:4]

array([[12, 13]])

In [ ]:
mat<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [ ]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [ ]:
mat[mat!=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
mat==50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [ ]:
mat[mat==50]

array([50])

# Python Program for generate OTP code